### ISSUE TITLE
build error: expected unqualified-id

### ISSUE THREAD

**Issue by Goyicho** [wdkk/iSuperColliderKit#2]
Hi,
I am trying to get this amazing kit running on my laptop. However, after I did every step as described, I am still getting `expected unqualified-id` error. It seems that it is caused by the `version` file in `external_libraries/libsndfile`. Any idea how to solve this?
Thanks!

update: I seem to fix this issue by renaming `VERSION` to `VERSION.txt`, but now I am getting other semantic issues like `external_libraries/boost/boost/functional/hash/extensions.hpp:160:24: Redefinition of 'hash_value' as different kind of symbol`

**Comment by wdkk-kengo** [comment]
Thank you for your comment.
When I build it with XCode 13.2.1, I do get a build error.

Please give me some time to investigate.
Thank you.

**Comment by wdkk-kengo** [comment]
Hello.
I've made it possible to build with XCode 13.2.1.
It is tagged with version 1.2.0.

The reason was that the code I was using was old. The C++ compiler of the new XCode was giving errors. Also, the VERSION that Goyicho gave me was the cause of the error. I responded by changing the version.txt file as well.

The updated version is shown below.
- Changed the supported version to iOS 12.0 or higher.
- Changed compiler to C++17
- Changed old code to support C++17
- Changed the project settings so that the .cpp resources pass through the Objective-C++ compiler.
- Changed memory management to support changes in the glob_t structure

However, the build went through, and we have only verified that the sine wave sounds on iOS15. Other problems may occur or there may be memory issues. I apologize if there are any problems.

The Super Collider code is also very old, so I may have to revise the whole thing.

Thank you for following me.
Keep up the good work.
